### ISSUE TITLE
"Voirinkeli" is not accepted.

### ISSUE THREAD

**Issue by ghost** [MaijaHeiskanen/sanapeli#1]

**Comment by Apezkin** [comment]
[https://www.kotus.fi/sanakirjat/kielitoimiston_sanakirja/uudet_sanat/ilmianna_sana!](https://www.kotus.fi/sanakirjat/kielitoimiston_sanakirja/uudet_sanat/ilmianna_sana!)

**Comment by MaijaHeiskanen** [comment]
https://www.kielitoimistonsanakirja.fi/#/voirinkeli?searchMode=all

Looks like "voirinkeli" is not an official Finnish word so the game works as expected. If you feel like this word shoud be accepted, you can try to get Kotus to add it: https://www.kotus.fi/sanakirjat/kielitoimiston_sanakirja/uudet_sanat/ilmianna_sana!

Let me know if the word "voirinkeli" is added and I will add it to the game too. Meanwhile, you can try words like "vesirinkeli" and "bagelrinkeli".
